theme: jekyll-theme-cayman
title: 心版 - 将神的话语刻在心版上
description: 帮助基督徒在手机主屏幕上展示圣经经文的 iOS 小组件应用
lang: zh-CN
defaults:
    - scope:
          path: '' # 应用到所有文件
      values:
          layout: 'default' # 使用我们的默认布局
